import {
  IconAntenna,
  IconAward,
  IconBallBaseball,
  IconBallVolleyball,
  IconBarbell,
  IconBallFootball,
  IconBallTennis,
  IconBook,
  IconBriefcase,
  IconBuildingBank,
  IconBuildingCommunity,
  IconCalendarEvent,
  IconCalendarWeek,
  IconCalendarMonth,
  IconCar,
  IconChartLine,
  IconCheckbox,
  IconChess,
  IconGolf,
  IconCircleCheck,
  IconCoin,
  IconCricket,
  IconDeviceMobile,
  IconDeviceTv,
  IconHeart,
  IconHeartHandshake,
  IconHeartbeat,
  IconHome,
  IconLeaf,
  IconLock,
  IconMapPin,
  IconMasksTheater,
  IconMedal,
  IconMicrophone,
  IconMotorbike,
  IconMovie,
  IconMusic,
  IconPencil,
  IconScale,
  IconPlane,
  IconPlayHandball,
  IconPlayerPlay,
  IconReceipt,
  IconReportAnalytics,
  IconRobot,
  IconRocket,
  IconRun,
  IconSchool,
  IconSeeding,
  IconShieldCheck,
  IconShirt,
  IconSparkles,
  IconStar,
  IconStretching,
  IconTarget,
  IconToolsKitchen2,
  IconTools,
  IconTournament,
  IconTrain,
  IconTrophy,
  IconUsersGroup,
  IconVideo,
  IconWheat,
  IconYoga,
  IconZoomCheck,
} from "@tabler/icons-react";
import type { ComponentType } from "react";

type IconComponent = ComponentType<{ className?: string; stroke?: number }>;

/** One vector icon per sub-topic — same flat, stroked style everywhere. */
export const topicIcons: Record<string, IconComponent> = {
  // sports
  cricket: IconCricket,
  football: IconBallFootball,
  hockey: IconGolf,
  kabaddi: IconPlayHandball,
  badminton: IconBallVolleyball,
  tennis: IconBallTennis,
  athletics: IconRun,
  wrestling: IconBarbell,
  chess: IconChess,
  olympics: IconMedal,
  // desh
  shiksha: IconSchool,
  swasthya: IconHeartbeat,
  railway: IconTrain,
  digital: IconAntenna,
  suraksha: IconShieldCheck,
  krishi: IconWheat,
  // rajniti
  loksabha: IconBuildingBank,
  rajyasabha: IconBuildingCommunity,
  chunav: IconCheckbox,
  vipaksh: IconUsersGroup,
  // cricket formats
  test: IconCricket,
  odi: IconBallBaseball,
  t20: IconTrophy,
  ipl: IconTournament,
  mahila: IconStretching,
  gharelu: IconBuildingCommunity,
  // manoranjan
  filmein: IconMovie,
  webseries: IconDeviceTv,
  sangeet: IconMusic,
  puraskar: IconAward,
  // vyapar
  bazaar: IconChartLine,
  startup: IconRocket,
  banking: IconBuildingBank,
  sona: IconCoin,
  tax: IconReceipt,
  // tech
  mobile: IconDeviceMobile,
  ai: IconRobot,
  car: IconCar,
  bike: IconMotorbike,
  cyber: IconLock,
  // tejaswini
  udyamita: IconSeeding,
  career: IconBriefcase,
  khel: IconMedal,
  prerna: IconSparkles,
  // investigation
  padtal: IconZoomCheck,
  ground: IconMapPin,
  factcheck: IconCircleCheck,
  // khaas
  paryavaran: IconLeaf,
  samaj: IconUsersGroup,
  sanskriti: IconMasksTheater,
  // originals
  documentary: IconVideo,
  series: IconBook,
  video: IconPlayerPlay,
  // jobs
  sarkari: IconBuildingBank,
  result: IconReportAnalytics,
  admission: IconSchool,
  skill: IconTools,
  // lifestyle
  sehat: IconHeart,
  fashion: IconShirt,
  khanpan: IconToolsKitchen2,
  yatra: IconPlane,
  ghar: IconHome,
  // jeevan mantra
  rishte: IconHeartHandshake,
  safalta: IconTarget,
  dhyan: IconYoga,
  // opinion
  sampadakiya: IconPencil,
  vishleshan: IconScale,
  column: IconMicrophone,
  // rashifal
  dainik: IconCalendarEvent,
  saptahik: IconCalendarWeek,
  masik: IconCalendarMonth,
  varshik: IconStar,
};
